language: node_js
git:
  depth: 3
node_js:
- node
install: npm install
script:
- npm test
- gulp
cache:
  directories:
  - node_modules
notifications:
  email: false
deploy:
  provider: firebase
  token:
    secure: "R+iR36gjxuyT3jqWVqIBLzzXdRNrAacCsWznb4JRqNfQSPMf0h9ZsmBOaEK+Rx1d2OLUcv+RWzwTW9IwnUy8Ei2tKpnd/fSMYjINUhxATVu9JKQxom/1J0B36u8S4FOvk0JuVcJLdLOJfz+C37XUCclnsYWNtitRwoA5sWh4IoTY3jl/lireCerhvRBjzN9PaqIwXojugruvHkfLNToF45USt7hU1x8uIw91/0II8moIWhw97lLzWp8OVCxutiZ0xXn1VmnQ+rgWljWjk98z5k1vcXRXW1nFxk56gIqdftbY/ZZZ/jfm88olXOFXhfkMXOrQHduNTImjKcBtai7wIuKOFJwzeClkya9zAb9aUGAtNKnFbBDwh94B1f5h4e+qO9o6PACGdjPErjW/3ycOgXBR1t4Jub3SdaNSm3bgyjaOjOqm8a+FUPDNza3RQDmrnGtPQrLqKpJKdEIcx03QhfHekVGU+RkveINUSJL794nRFtzA2apSW1Zxq0xxPvm10nfZEB7l2JedSybHey4aKC08n3kFw6UBzMTDWgcvo4RBqxVkhcv/fC400M+Qfm48t9tdtcIlWH4FKLNCoHBPMIgjA5L+w4UZY+fqX5nEdCo5SJWm8JrECKW/0ujdPbOWzQ4w4b3874ugfP5JERlV3rzwsCS+1P0AsJS9mhiivy8="
  project: elevenna
